[tool.poetry]
name = "OT-projekti"
version = "0.1.7.1"
description = ""
authors = ["keranenkirill <keranen.kirill@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
