import budget_app_db

budget_app_db.create_tables()
print()
print()
print("LISÄTÄÄN KÄYTTÄJÄ:")
user_id=budget_app_db.create_user("ErkKa", "NappiKukkaro01")
#print("    ",user_id)
print()
print()
print("LISÄTÄÄN EXPENCE:")
budget_app_db.add_expence(40, "dna lasku", user_id)
budget_app_db.add_expence(680, "vuokra", user_id)
budget_app_db.add_expence(11, "netflix", user_id)
budget_app_db.add_expence(8, "spotify", user_id)
budget_app_db.add_expence(13, "kotinetti", user_id)
budget_app_db.add_expence(550, "sijoitukset", user_id)
budget_app_db.add_expence(300, "vapaa-ajan kulut", user_id)
print()
print()
print("LISÄTÄÄN INCOME:")
budget_app_db.add_income("kela", 340,user_id)
budget_app_db.add_income("palkka", 1560, user_id)
print()
print()
print("HAETAAN KÄYTTÄJÄN KAIKKI KULUT:")
budget_app_db.get_all_expenses(user_id)
print()
print()
print("HAETAAN KÄYTTÄJÄN  KULUJEN YHTEISSUMMA:")
budget_app_db.get_summ_of_all_expenses(user_id)
print()
print()
print("HAETAAN KÄYTTÄJÄN KAIKKI TULOT:")
budget_app_db.get_all_incomes(user_id)
print()
print()
print("HAETAAN KÄYTTÄJÄN  TULOJEN YHTEISSUMMA:")
budget_app_db.get_summ_of_all_incomes(user_id)
print()
print()
print("HAETAAN KÄYTTÄJÄN  TULOJEN JA MENOJEN EROTUS:")
budget_app_db.get_income_expense_diff(user_id)

